table HOQ_RULE_TYPE
	lineageTag: 2ecd7111-8504-4586-bcc2-c66d36096dbd

	column HOQ_RULE_TYPE_CODE
		dataType: string
		lineageTag: 0a693eb1-99b1-4c31-9a85-64cf009731c2
		summarizeBy: none
		sourceColumn: HOQ_RULE_TYPE_CODE

		annotation SummarizationSetBy = Automatic

	column 'Rule Type'
		dataType: string
		lineageTag: 69a3c150-8aa1-4ec3-a8e4-401daf40c003
		summarizeBy: none
		sourceColumn: Rule Type

		annotation SummarizationSetBy = Automatic

	column CREATED_DATETIME
		dataType: dateTime
		formatString: General Date
		lineageTag: efbfa7cc-d607-46ff-af91-3e3daafeb012
		summarizeBy: none
		sourceColumn: CREATED_DATETIME

		variation Variation
			isDefault
			relationship: 1d82f585-94b8-46a5-b6bc-f14419675dfd
			defaultHierarchy: LocalDateTable_7f6b8590-7dc4-4487-9748-b5a686f0d1b6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column CREATED_BY_NAME
		dataType: string
		lineageTag: 35adeccb-f5d4-4ddb-92a8-abd48c5fe746
		summarizeBy: none
		sourceColumn: CREATED_BY_NAME

		annotation SummarizationSetBy = Automatic

	column CREATED_BY_COMMENTS
		dataType: string
		lineageTag: 99485b1f-9ddb-4686-ac50-fd9d49732b7e
		summarizeBy: none
		sourceColumn: CREATED_BY_COMMENTS

		annotation SummarizationSetBy = Automatic

	column MODIFIED_DATETIME
		dataType: dateTime
		formatString: General Date
		lineageTag: 52e54fb8-5a48-4e73-a02d-e2310bccbdf9
		summarizeBy: none
		sourceColumn: MODIFIED_DATETIME

		variation Variation
			isDefault
			relationship: bd31e1bd-391e-41b9-84f0-3baad3680204
			defaultHierarchy: LocalDateTable_388f3696-9176-48b2-b74e-33f72e7e548f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column MODIFIED_BY_NAME
		dataType: string
		lineageTag: c4902bfd-7710-4034-bc6b-e0fd159cf8ed
		summarizeBy: none
		sourceColumn: MODIFIED_BY_NAME

		annotation SummarizationSetBy = Automatic

	column MODIFIED_BY_COMMENTS
		dataType: string
		lineageTag: fcc8f56e-18ed-4605-a0f2-b0862f28bbd6
		summarizeBy: none
		sourceColumn: MODIFIED_BY_COMMENTS

		annotation SummarizationSetBy = Automatic

	partition HOQ_RULE_TYPE = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(snowflake_url,"ANALYST_WH_XS"),
				    HUB_Database = Source{[Name="HUB",Kind="Database"]}[Data],
				    JOB_Schema = HUB_Database{[Name="JOB",Kind="Schema"]}[Data],
				    HOQ_RULE_TYPE_Table = JOB_Schema{[Name="HOQ_RULE_TYPE",Kind="Table"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(HOQ_RULE_TYPE_Table,{{"HOQ_RULE_TYPE_NAME", "Rule Type"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

