table HOLDING_IBOXX
	lineageTag: cc86b28b-b1be-49ca-99be-682f78a6b2e7

	measure 'IBOXX MV + AI Measure' = sum(HOLDING_IBOXX[IBOXX MV (Dirty)])
		lineageTag: 3c7174de-af0c-4930-9f79-81c750bf5598

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'IBOXX MV (Mid Clean)' = ```
			SUMX(
			    'HOLDING_IBOXX',
			    'HOLDING_IBOXX'[IBOXX Notional] * 
			    IF(
			        ISBLANK(DIVIDE(RELATED('INSTRUMENT_OFFICIAL_PRICE'[Mid Price]), 100)),
			        1,
			        DIVIDE(RELATED('INSTRUMENT_OFFICIAL_PRICE'[Mid Price]), 100)
			    )
			)
			
			```
		lineageTag: fc37dc26-f2fb-4bc3-8b52-8278a0e5a4ce

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'IBOXX MV % (Clean - Cash)' = ```
			
			IF(
			    HOLDING_IBOXX[IBOXX MV (Mid Clean)] = BLANK(),
			    BLANK(),
			    DIVIDE(
			        SUMX(
			    FILTER(
			        HOLDING_IBOXX,
			        HOLDING_IBOXX[Instrument Identifier] <> "96c3f10ecbc02bf14bdee5a10eebf998"
			    ),
			    HOLDING_IBOXX[IBOXX MV (Mid Clean)]
			), 
			        CALCULATE(
			            HOLDING_IBOXX[IBOXX MV (Mid Clean)] ,
			            filter(ALL(HOLDING_IBOXX),'HOLDING_IBOXX'[Instrument Identifier] <> "96c3f10ecbc02bf14bdee5a10eebf998")
			        ),
			        
			        BLANK()
			    )
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0e39db47-e609-44f2-a7a2-37d6725e9f89

	column 'Period End Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: a8c27553-fc76-4f00-85f7-ffe88c30c091
		summarizeBy: none
		sourceColumn: Period End Date

		variation Variation
			isDefault
			relationship: 240ec65c-4d40-4eaa-bd66-0bed41bbc2ab
			defaultHierarchy: LocalDateTable_db276312-e374-4489-bb76-197b557d0cdc.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SOURCE_SYSTEM_CODE
		dataType: string
		isHidden
		lineageTag: 69b651e5-f83b-4283-b121-82b4421dc7da
		summarizeBy: none
		sourceColumn: SOURCE_SYSTEM_CODE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SOURCE_SYSTEM_SHORT_NAME
		dataType: string
		isHidden
		lineageTag: 8da156d9-9052-41e4-a1eb-385f4d9e9c37
		summarizeBy: none
		sourceColumn: SOURCE_SYSTEM_SHORT_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SOURCE_SYSTEM_NAME
		dataType: string
		isHidden
		lineageTag: bea6ca38-23bc-44ee-b796-9949fcb4aa35
		summarizeBy: none
		sourceColumn: SOURCE_SYSTEM_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Instrument Identifier'
		dataType: string
		lineageTag: 00cba9d9-f5b3-4066-8b4d-c36b8aa4896e
		summarizeBy: none
		sourceColumn: Instrument Identifier

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PORTFOLIO_IDENTIFIER
		dataType: string
		isHidden
		lineageTag: 58db0c0d-2dcd-4497-9316-59243896cba4
		summarizeBy: none
		sourceColumn: PORTFOLIO_IDENTIFIER

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CUSTODIAN_ACCOUNT_IDENTIFIER
		dataType: string
		isHidden
		lineageTag: b4b2a64b-0519-4782-8953-ae0158eb54f5
		summarizeBy: none
		sourceColumn: CUSTODIAN_ACCOUNT_IDENTIFIER

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'IBOXX Notional'
		dataType: double
		formatString: #,0
		lineageTag: 2f7432f5-bcf0-4b1d-81c1-48d2b7a5762f
		summarizeBy: sum
		sourceColumn: IBOXX Notional

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column ORIGINAL_FACE_AMOUNT
		dataType: double
		isHidden
		lineageTag: 285d49eb-8fc6-42c5-8aee-615b20931a45
		summarizeBy: sum
		sourceColumn: ORIGINAL_FACE_AMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CURRENT_FACE_AMOUNT
		dataType: double
		lineageTag: 91d1a036-ea93-4def-b5a9-359e3b704a7f
		summarizeBy: sum
		sourceColumn: CURRENT_FACE_AMOUNT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'IBOXX MV (Dirty)'
		dataType: double
		formatString: #,0
		lineageTag: b31cf6ee-64c6-46ea-a770-a19d77ed03b5
		summarizeBy: sum
		sourceColumn: IBOXX MV (Dirty)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column MV_LOCAL_AMOUNT
		dataType: double
		isHidden
		lineageTag: 3adbdf62-9882-426b-8b86-0e5d37dbadf3
		summarizeBy: sum
		sourceColumn: MV_LOCAL_AMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'IBOXX AI'
		dataType: double
		formatString: #,0
		lineageTag: aaa1a4d1-5c27-4511-b0c3-3dab3670add8
		summarizeBy: sum
		sourceColumn: IBOXX AI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column ACCRUED_LOCAL_AMOUNT
		dataType: double
		isHidden
		lineageTag: 8216c474-3653-4d7c-9185-75afb720d9e3
		summarizeBy: sum
		sourceColumn: ACCRUED_LOCAL_AMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COST_BASIS_HOME_AMOUNT
		dataType: double
		isHidden
		lineageTag: ed49afc8-357d-4551-87ab-05ec19ea3e2d
		summarizeBy: sum
		sourceColumn: COST_BASIS_HOME_AMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COST_BASIS_LOCAL_AMOUNT
		dataType: double
		isHidden
		lineageTag: 7fbbe4ae-a10c-4270-9f61-1f177f9c17bb
		summarizeBy: sum
		sourceColumn: COST_BASIS_LOCAL_AMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CURRENCY_CODE
		dataType: string
		isHidden
		lineageTag: 48824911-72eb-4151-83bb-3d735534415d
		summarizeBy: none
		sourceColumn: CURRENCY_CODE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PRICE_DATE
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 0791ca2d-e380-4fc9-a5f4-6af2f75ddc8d
		summarizeBy: none
		sourceColumn: PRICE_DATE

		variation Variation
			isDefault
			relationship: 07d3514e-fb6a-4f71-8f35-a16bfeeef530
			defaultHierarchy: LocalDateTable_dbc59e08-748d-423a-ae03-35c549a5dea2.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Price Home Amount'
		dataType: double
		lineageTag: 3685cf7f-138b-4700-bcff-e364c6f36297
		summarizeBy: sum
		sourceColumn: Price Home Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PRICE_LOCAL_AMOUNT
		dataType: double
		isHidden
		lineageTag: b78dcac9-b421-4f3b-81e4-d2716d7d0433
		summarizeBy: sum
		sourceColumn: PRICE_LOCAL_AMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PRICE_SOURCE_NAME
		dataType: string
		isHidden
		lineageTag: 5514fc2e-5f15-4fdf-8766-3842ec2cae77
		summarizeBy: none
		sourceColumn: PRICE_SOURCE_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'FX Rate'
		dataType: double
		isHidden
		lineageTag: 50dd7f1f-d65c-4ede-8fe7-baa449299195
		summarizeBy: sum
		sourceColumn: FX Rate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Portfolio Holding Percent'
		dataType: double
		lineageTag: 83945480-3e63-4c7d-a887-8b062237d63a
		summarizeBy: sum
		sourceColumn: Portfolio Holding Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REDEMPTION_FACTOR
		dataType: double
		isHidden
		lineageTag: f13fd943-31b9-4279-81af-27d6c329717d
		summarizeBy: sum
		sourceColumn: REDEMPTION_FACTOR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SOURCE_SYSTEM_STATUS_IDENTIFIER
		dataType: double
		isHidden
		lineageTag: 7d63899d-7caf-4332-ab4c-f6736b60b1e1
		summarizeBy: sum
		sourceColumn: SOURCE_SYSTEM_STATUS_IDENTIFIER

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ENDING_NAV_AMOUNT
		dataType: double
		isHidden
		lineageTag: e6773af2-2a73-4a63-a294-f9ee7960f5e8
		summarizeBy: sum
		sourceColumn: ENDING_NAV_AMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BEGINNING_NAV_AMOUNT
		dataType: double
		isHidden
		lineageTag: a31a2618-f8f7-47e6-9f6c-6bd39c82df34
		summarizeBy: sum
		sourceColumn: BEGINNING_NAV_AMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UNFUNDED_COMMITMENT_LOCAL
		dataType: double
		isHidden
		lineageTag: 60b2805f-400f-4cd4-82e8-7189ee3ae4bb
		summarizeBy: sum
		sourceColumn: UNFUNDED_COMMITMENT_LOCAL

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CREATED_DATETIME
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 3030d8f4-37e7-4404-a4f1-d26e8a56b3ef
		summarizeBy: none
		sourceColumn: CREATED_DATETIME

		variation Variation
			isDefault
			relationship: 3ad5a3e8-2823-44f6-9bf2-68bdb9162cce
			defaultHierarchy: LocalDateTable_8ba75e2d-1fba-41ef-8ef6-b879410af2cf.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CREATED_BY_NAME
		dataType: string
		isHidden
		lineageTag: 873bb675-7535-49c3-9c43-0c305e6d8b61
		summarizeBy: none
		sourceColumn: CREATED_BY_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CREATED_BY_COMMENTS
		dataType: string
		isHidden
		lineageTag: 935fcfe6-2743-4627-bad6-a687ecf4afc6
		summarizeBy: none
		sourceColumn: CREATED_BY_COMMENTS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MODIFIED_DATETIME
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 493d3c9e-3ae2-4395-b009-9a8e06c65192
		summarizeBy: none
		sourceColumn: MODIFIED_DATETIME

		variation Variation
			isDefault
			relationship: 915ca5d2-df8d-4879-a1c4-c089078e3b4f
			defaultHierarchy: LocalDateTable_861861c7-5896-4dc7-a788-d2490ee738bd.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MODIFIED_BY_NAME
		dataType: string
		isHidden
		lineageTag: 8fd4c5de-c4c8-4922-968e-4543ea5d698d
		summarizeBy: none
		sourceColumn: MODIFIED_BY_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MODIFIED_BY_COMMENTS
		dataType: string
		isHidden
		lineageTag: 242bac45-cd15-4e94-bff8-0ff7ef572202
		summarizeBy: none
		sourceColumn: MODIFIED_BY_COMMENTS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ID_DATE
		dataType: string
		lineageTag: cb78154e-cf4b-4e7d-a460-e0d6e43f540c
		summarizeBy: none
		sourceColumn: ID_DATE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ID_DATE_PORT
		dataType: string
		isHidden
		lineageTag: 7c6790ee-87e3-4a45-b2bc-5da3ecfd617c
		summarizeBy: none
		sourceColumn: ID_DATE_PORT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column POSITION_SETTLED_QUANTITY
		dataType: double
		lineageTag: a8be5a0e-0a77-4a43-8751-32b5cb9888f4
		summarizeBy: sum
		sourceColumn: POSITION_SETTLED_QUANTITY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'IBOXX MV % (Dirty)' =
			
			
			IF(
			    HOLDING_IBOXX[IBOXX MV (Dirty)] = BLANK(),
			    BLANK(),
			    DIVIDE(
			      HOLDING_IBOXX[IBOXX MV (Dirty)],
			      CALCULATE(
			         sum(HOLDING_IBOXX[IBOXX MV (Dirty)]),
			         ALLSELECTED(HOLDING_IBOXX)
			        )+0
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0dc40a4d-886e-454f-99b2-7a561edc30f5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'IBOXX Notional %' =
			
			IF(
			    HOLDING_IBOXX[IBOXX Notional] = BLANK(),
			    BLANK(),
			    DIVIDE(
			        HOLDING_IBOXX[IBOXX Notional],
			        CALCULATE(
			            sum(HOLDING_IBOXX[IBOXX Notional]),
			            ALL(HOLDING_IBOXX)
			        ),
			        BLANK()
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: d306f248-90e3-46fa-b822-f7c6b1f8f2e5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'IBOXX MV + AI' = ```
			HOLDING_IBOXX[IBOXX MV (Dirty)] + HOLDING_IBOXX[IBOXX AI] 
			```
		lineageTag: 75d26d73-d3d9-4fd1-adb2-9ad98022084f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'IBOXX MV (Dirty) + AI %' =
			
			IF(
			    HOLDING_IBOXX[IBOXX MV + AI Measure] = BLANK(),
			    BLANK(),
			    DIVIDE(
			        HOLDING_IBOXX[IBOXX MV + AI Measure],
			        CALCULATE(
			            HOLDING_IBOXX[IBOXX MV + AI Measure],
			            ALL(HOLDING_IBOXX)
			        ),
			        BLANK()
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 37ec31c3-c198-433f-9b60-091b0c6073f5
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column SENTRY_PORTFOLIO_IDENTIFIER
		dataType: string
		lineageTag: 87229444-24be-4973-bbe4-71818f89738b
		summarizeBy: none
		sourceColumn: SENTRY_PORTFOLIO_IDENTIFIER

		annotation SummarizationSetBy = Automatic

	column DATA_PROVIDER_NAME
		dataType: string
		lineageTag: ab1e158c-6e9b-40d7-a3fa-bc1b225c3bf2
		summarizeBy: none
		sourceColumn: DATA_PROVIDER_NAME

		annotation SummarizationSetBy = Automatic

	column VANTAGE_PORTFOLIO_IDENTIFIER
		dataType: string
		lineageTag: f5a5c6cb-b37d-4b16-abe3-f92a505a3c64
		summarizeBy: none
		sourceColumn: VANTAGE_PORTFOLIO_IDENTIFIER

		annotation SummarizationSetBy = Automatic

	column VANTAGE_CUSTODIAN_ACCOUNT_IDENTIFIER
		dataType: string
		lineageTag: 577ef79b-5a6a-4ea1-bd97-488ed93d7e49
		summarizeBy: none
		sourceColumn: VANTAGE_CUSTODIAN_ACCOUNT_IDENTIFIER

		annotation SummarizationSetBy = Automatic

	column 'IBOXX MV % (Dirty) Column' =
			
			DIVIDE(
			    HOLDING_IBOXX[IBOXX MV (Dirty)],
			    CALCULATE(
			        SUM(HOLDING_IBOXX[IBOXX MV (Dirty)]),
			        ALLSELECTED(HOLDING_IBOXX)
			    )
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f45a0284-39ce-4fe1-8d8d-63d73e224db1
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition HOLDING_IBOXX = m
		mode: import
		source =
				let
				    Source = HOLDING,
				    #"Filtered Rows1" = Table.SelectRows(Source, each ([PORTFOLIO_IDENTIFIER] = "IBOXLTRI")),
				    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows1",{{"MV Home Amount", "IBOXX MV (Dirty)"}, {"Position Quantity", "IBOXX Notional"}, {"Accrued", "IBOXX AI"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

