table INSTRUMENT_RATING_SENTRY_SPGLOBAL
	isHidden
	lineageTag: 546cd91a-4a16-40d2-ad45-69089afc37cb

	column 'Calendar Date'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: e8df900c-55b9-49a7-a2ad-dd925477c44b
		summarizeBy: none
		sourceColumn: Calendar Date

		variation Variation
			isDefault
			relationship: ef2b0a36-38e3-494a-a273-28dfb93e2259
			defaultHierarchy: LocalDateTable_33f01799-2972-4143-8b94-8270e14e37c4.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column INSTRUMENT_IDENTIFIER
		dataType: string
		isHidden
		lineageTag: 408707b3-a159-45d3-8298-6dd0bb4aa897
		summarizeBy: none
		sourceColumn: INSTRUMENT_IDENTIFIER

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ISSUER_IDENTIFIER
		dataType: string
		isHidden
		lineageTag: cb8369b6-7656-40d4-8bbe-3e675ec4889b
		summarizeBy: none
		sourceColumn: ISSUER_IDENTIFIER

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Data Provider Name'
		dataType: string
		isHidden
		lineageTag: 1c68c3c8-0b84-4b6f-9bb2-d61617d09e4f
		summarizeBy: none
		sourceColumn: Data Provider Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Rating
		dataType: string
		isHidden
		lineageTag: b39e8aa4-db79-49c9-9598-5700a8ff0bf9
		summarizeBy: none
		sourceColumn: Rating

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Rating Date'
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 99743c8b-08e5-4494-b5f6-47191b65d2a8
		summarizeBy: none
		sourceColumn: Rating Date

		variation Variation
			isDefault
			relationship: 2dbc1bb5-5177-4755-9a8a-17a39116975a
			defaultHierarchy: LocalDateTable_c7678026-29dd-48ed-bfea-ee9b3dfbb8e6.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Effective Start Date'
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 24a5c5fb-86fb-4aef-9566-44624373f485
		summarizeBy: none
		sourceColumn: Effective Start Date

		variation Variation
			isDefault
			relationship: 0fa48fa9-afbe-4efc-8bd6-dcf61c649d5c
			defaultHierarchy: LocalDateTable_6a11166a-e92c-4858-af77-d64ec37cc4ad.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Effective End Date'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: f7be8dc7-6a48-4518-ab84-eecdb3ccf82a
		summarizeBy: none
		sourceColumn: Effective End Date

		variation Variation
			isDefault
			relationship: 788720bf-1b8e-422c-aceb-9b8e3c21ebed
			defaultHierarchy: LocalDateTable_0d12698f-bfe3-4168-a915-4b51002c8f43.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Rating Action'
		dataType: string
		isHidden
		lineageTag: 602a89b7-c6c3-4719-b41f-f10d3fc6be25
		summarizeBy: none
		sourceColumn: Rating Action

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Credit Watch'
		dataType: string
		isHidden
		lineageTag: 3ebd2daf-9a3e-4787-a2ba-c24a62a45543
		summarizeBy: none
		sourceColumn: Credit Watch

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Credit Watch Date'
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: f8413bfa-5b87-417a-91bf-8c2a96e4b51a
		summarizeBy: none
		sourceColumn: Credit Watch Date

		variation Variation
			isDefault
			relationship: 071e0123-ed68-4c43-90a7-dbf53f3f3846
			defaultHierarchy: LocalDateTable_d10498ce-6abd-4b51-8d0b-f669bea2104e.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Outlook
		dataType: string
		isHidden
		lineageTag: b9023046-5faf-4532-82c0-e821f8707b53
		summarizeBy: none
		sourceColumn: Outlook

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Outlook Date'
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: e83c1eb6-7bcf-4155-9d3e-7b6968a78161
		summarizeBy: none
		sourceColumn: Outlook Date

		variation Variation
			isDefault
			relationship: 634eb5fa-344f-4b40-a235-641e85a694b0
			defaultHierarchy: LocalDateTable_385bb1fe-2f09-43f9-be20-18753bab47f4.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Recovery Rating'
		dataType: string
		isHidden
		lineageTag: 0f14b808-a60a-411b-b854-34a8b4f2b882
		summarizeBy: none
		sourceColumn: Recovery Rating

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Recovery Rating Date'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 5059787e-386a-46ad-a000-578bfcc63126
		summarizeBy: none
		sourceColumn: Recovery Rating Date

		variation Variation
			isDefault
			relationship: 0e557974-d6f0-4310-b2de-102d006c2164
			defaultHierarchy: LocalDateTable_d10c7ba5-3d5b-4719-8c91-ec60ae3cfdf7.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Issuer Rating'
		dataType: string
		isHidden
		lineageTag: 7619ccab-2404-4089-bf4c-d7827be36f9b
		summarizeBy: none
		sourceColumn: Issuer Rating

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Issuer Rating Date'
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: ce721a4f-f580-418c-9e6b-3532785ce5d2
		summarizeBy: none
		sourceColumn: Issuer Rating Date

		variation Variation
			isDefault
			relationship: 9fb7a99b-0560-4671-a759-6fd68fff85ef
			defaultHierarchy: LocalDateTable_c14b227c-2a21-4d76-a3fe-e0c10f68b0af.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Issuer Rating Effective Start Date'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 15f91c93-b3db-45c2-80b0-4ebe6dc1a7f3
		summarizeBy: none
		sourceColumn: Issuer Rating Effective Start Date

		variation Variation
			isDefault
			relationship: f2c64d78-1443-452b-8035-c3f883c007b3
			defaultHierarchy: LocalDateTable_64367776-60d3-414d-9a86-206171d6bea9.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ISSUER_RATING_EFFECTIVE_END_DATE
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: a58ec521-d6b1-44eb-adae-61508f6b7991
		summarizeBy: none
		sourceColumn: ISSUER_RATING_EFFECTIVE_END_DATE

		variation Variation
			isDefault
			relationship: c76b82c9-caa6-405a-b59e-b263b8400320
			defaultHierarchy: LocalDateTable_20d609d2-ad1a-4013-b716-7df2e30fa8ab.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Issuer Rating Action Description'
		dataType: string
		isHidden
		lineageTag: 6c054b88-9bfa-4a40-a1d0-b2160f6c85c7
		summarizeBy: none
		sourceColumn: Issuer Rating Action Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Issuer Credit Watch'
		dataType: string
		isHidden
		lineageTag: ef464454-108e-4406-9d8a-30694e691efe
		summarizeBy: none
		sourceColumn: Issuer Credit Watch

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Issuer Credit Watch Date'
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 58e7cd84-f125-43ea-b9b3-e2a41f43fdd5
		summarizeBy: none
		sourceColumn: Issuer Credit Watch Date

		variation Variation
			isDefault
			relationship: c07345c4-0932-4b0b-850b-cbf9e1b19865
			defaultHierarchy: LocalDateTable_f73a9f82-b730-4c36-af78-1c3a91a5a6e1.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Issuer Outlook'
		dataType: string
		isHidden
		lineageTag: 22b8b18a-3c69-42ff-ba27-c516403f5027
		summarizeBy: none
		sourceColumn: Issuer Outlook

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Issuer Outlook Date'
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: bcb1b06a-0752-4b60-99cc-f3b14a6c134c
		summarizeBy: none
		sourceColumn: Issuer Outlook Date

		variation Variation
			isDefault
			relationship: 02338996-c73f-44d3-80c3-658528bbb5ed
			defaultHierarchy: LocalDateTable_7961616d-353e-43ff-9833-506417eaadf4.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RATING_CODE_DATA_PROVIDER_NAME
		dataType: string
		isHidden
		lineageTag: e5bee991-cc18-4680-af0a-bb1ee6669eaf
		summarizeBy: none
		sourceColumn: RATING_CODE_DATA_PROVIDER_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ISSUER_RATING_CODE_DATA_PROVIDER_NAME
		dataType: string
		isHidden
		lineageTag: 32dce073-c891-4b88-9d7b-4d7c0fb9ad23
		summarizeBy: none
		sourceColumn: ISSUER_RATING_CODE_DATA_PROVIDER_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Rating Number'
		dataType: double
		isHidden
		lineageTag: b1b98140-9efc-4029-a1cf-49ba8730a15d
		summarizeBy: sum
		sourceColumn: Rating Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RATING_FACTOR
		dataType: double
		isHidden
		lineageTag: 196a0637-bac3-4442-977c-b337de96e4cb
		summarizeBy: sum
		sourceColumn: RATING_FACTOR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ISSUER_RATING_NUMBER
		dataType: double
		isHidden
		lineageTag: e910eb97-14c3-4ffa-bc07-3d85ff64ab9f
		summarizeBy: sum
		sourceColumn: ISSUER_RATING_NUMBER

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ISSUER_RATING_FACTOR
		dataType: double
		isHidden
		lineageTag: aa69afbd-4f92-4ebd-b400-c94e494e67f8
		summarizeBy: sum
		sourceColumn: ISSUER_RATING_FACTOR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ID_DATE
		dataType: string
		isHidden
		lineageTag: 96f4d4d5-1ee9-4e22-bcbc-d453f1782645
		summarizeBy: none
		sourceColumn: ID_DATE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition INSTRUMENT_RATING_SENTRY_SPGLOBAL = m
		mode: import
		source =
				let
				    Source = INSTRUMENT_RATING,
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Data Provider Name] = "SENTRY-SPGLOBAL"))
				in
				    #"Filtered Rows"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

