table INSTRUMENT_LIQUIDITY_SPGLOBAL
	isHidden
	lineageTag: 3e6d36de-9e9b-4e84-8f7c-12d6a1579fc0

	column 'Calendar Date'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: cb2f8df5-c38e-48e7-8830-c295da6ce2ff
		summarizeBy: none
		sourceColumn: Calendar Date

		variation Variation
			isDefault
			relationship: 2bdc44fe-db61-4f44-8e47-b0f9b6ced4fd
			defaultHierarchy: LocalDateTable_6113056d-91c7-4ffc-ac0e-47f520b175aa.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column INSTRUMENT_IDENTIFIER
		dataType: string
		isHidden
		lineageTag: a71a6cd8-7089-4196-854b-93aab2f27383
		summarizeBy: none
		sourceColumn: INSTRUMENT_IDENTIFIER

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Data Provider Name'
		dataType: string
		isHidden
		lineageTag: 1a88b95e-6e89-405e-9782-9af03b63e24e
		summarizeBy: none
		sourceColumn: Data Provider Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Liquidity Score'
		dataType: double
		isHidden
		formatString: 0
		lineageTag: 5c9913e5-caed-4f0f-84bb-3065b58c41d2
		summarizeBy: sum
		sourceColumn: Liquidity Score

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Liquidity Score 7 Day'
		dataType: double
		isHidden
		formatString: 0.00
		lineageTag: d162ed03-54fa-41c6-ab0a-54ba0ebc36c8
		summarizeBy: sum
		sourceColumn: Liquidity Score 7 Day

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Liquidity Score 30 Day'
		dataType: double
		isHidden
		formatString: 0.00
		lineageTag: 0ebd2d69-54eb-41fa-a032-5907561a7313
		summarizeBy: sum
		sourceColumn: Liquidity Score 30 Day

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Liquidity Score 60 Day'
		dataType: double
		isHidden
		formatString: 0.00
		lineageTag: f08077ba-23a5-4317-96cb-7db2427930f1
		summarizeBy: sum
		sourceColumn: Liquidity Score 60 Day

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Liquidity Score 90 Day'
		dataType: double
		isHidden
		formatString: 0.00
		lineageTag: 2eb3514f-bf37-4ca5-9ace-00b6f2aa3c9b
		summarizeBy: sum
		sourceColumn: Liquidity Score 90 Day

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Quote Spread'
		dataType: double
		isHidden
		lineageTag: d31b21cb-a74d-4acc-a4f4-c3c052729aee
		summarizeBy: sum
		sourceColumn: Quote Spread

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUOTE_SPREAD_7_DAY
		dataType: double
		isHidden
		lineageTag: 7547f739-c984-486b-92fb-73c9ea0f82a2
		summarizeBy: sum
		sourceColumn: QUOTE_SPREAD_7_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUOTE_SPREAD_30_DAY
		dataType: double
		isHidden
		lineageTag: 7a8d8e56-d17e-417d-ae39-36763290250e
		summarizeBy: sum
		sourceColumn: QUOTE_SPREAD_30_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUOTE_SPREAD_60_DAY
		dataType: double
		isHidden
		lineageTag: 650ae66b-dbb5-4253-9ab4-7c32100cbc8c
		summarizeBy: sum
		sourceColumn: QUOTE_SPREAD_60_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUOTE_SPREAD_90_DAY
		dataType: double
		isHidden
		lineageTag: 63e31227-5c4a-4fe6-9d52-52536195b8d5
		summarizeBy: sum
		sourceColumn: QUOTE_SPREAD_90_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Quote Depth'
		dataType: double
		isHidden
		lineageTag: 927332f1-2cc2-4fb8-a547-4f67b2bea1f2
		summarizeBy: sum
		sourceColumn: Quote Depth

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUOTE_DEPTH_TEXT
		dataType: double
		isHidden
		lineageTag: 6c9e7e0b-20ba-4000-a9cd-e670bf3299d3
		summarizeBy: sum
		sourceColumn: QUOTE_DEPTH_TEXT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Quote Depth 7 Day'
		dataType: double
		isHidden
		lineageTag: e8c18e10-3fd8-4589-92a8-5518a5939fc0
		summarizeBy: sum
		sourceColumn: Quote Depth 7 Day

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Quote Depth 30 Day'
		dataType: double
		isHidden
		lineageTag: dd63cd1b-403b-4f4f-9cc6-20dfab3bf49b
		summarizeBy: sum
		sourceColumn: Quote Depth 30 Day

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Quote Depth 60 Day'
		dataType: double
		isHidden
		lineageTag: 324e9338-7d6a-4815-943f-020e8c28e6e7
		summarizeBy: sum
		sourceColumn: Quote Depth 60 Day

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Quote Depth 90 Day'
		dataType: double
		isHidden
		lineageTag: 3bb8dcdd-c1da-486a-bcef-4c04e6d5fe65
		summarizeBy: sum
		sourceColumn: Quote Depth 90 Day

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUOTE_SIZE
		dataType: double
		isHidden
		lineageTag: 93399a23-ce5b-49f4-9b51-70092c56e15f
		summarizeBy: sum
		sourceColumn: QUOTE_SIZE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUOTE_SIZE_7_DAY
		dataType: double
		isHidden
		lineageTag: 15bf65e7-2175-4acc-91da-b8a243e5392e
		summarizeBy: sum
		sourceColumn: QUOTE_SIZE_7_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUOTE_SIZE_30_DAY
		dataType: double
		isHidden
		lineageTag: 07b509b4-6bab-4523-b54a-c2345ec0d016
		summarizeBy: sum
		sourceColumn: QUOTE_SIZE_30_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUOTE_SIZE_60_DAY
		dataType: double
		isHidden
		lineageTag: 9acc85cc-17a9-4be8-b60f-3ad6964ac0b8
		summarizeBy: sum
		sourceColumn: QUOTE_SIZE_60_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUOTE_SIZE_90_DAY
		dataType: double
		isHidden
		lineageTag: 056cc748-e0f2-48b3-9259-d6350e479569
		summarizeBy: sum
		sourceColumn: QUOTE_SIZE_90_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUOTE_MESSAGES_COUNT
		dataType: double
		isHidden
		lineageTag: 6e74510b-78dc-4276-af42-7dbbe30f411f
		summarizeBy: sum
		sourceColumn: QUOTE_MESSAGES_COUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUOTE_MESSAGES_COUNT_7_DAY
		dataType: double
		isHidden
		lineageTag: ccab35c7-6e19-4f86-ac10-13b9c93bf4ff
		summarizeBy: sum
		sourceColumn: QUOTE_MESSAGES_COUNT_7_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUOTE_MESSAGES_COUNT_30_DAY
		dataType: double
		isHidden
		lineageTag: fe71af70-8d8d-4ec0-bb51-2af7d37bc87b
		summarizeBy: sum
		sourceColumn: QUOTE_MESSAGES_COUNT_30_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUOTE_MESSAGES_COUNT_60_DAY
		dataType: double
		isHidden
		lineageTag: 9f223cee-b8b0-4245-8e4d-ba64a9f8fa76
		summarizeBy: sum
		sourceColumn: QUOTE_MESSAGES_COUNT_60_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUOTE_MESSAGES_COUNT_90_DAY
		dataType: double
		isHidden
		lineageTag: d78715dd-8524-4fbe-8366-37a8074885e1
		summarizeBy: sum
		sourceColumn: QUOTE_MESSAGES_COUNT_90_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUOTE_SOURCES_COUNT
		dataType: double
		isHidden
		lineageTag: 7326d3e9-d0ce-4b41-9a59-012747a536e5
		summarizeBy: sum
		sourceColumn: QUOTE_SOURCES_COUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUOTE_SOURCES_COUNT_7_DAY
		dataType: double
		isHidden
		lineageTag: 1da8e5ee-1594-4173-b9a0-d0eeb0f61b31
		summarizeBy: sum
		sourceColumn: QUOTE_SOURCES_COUNT_7_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUOTE_SOURCES_COUNT_30_DAY
		dataType: double
		isHidden
		lineageTag: bc17b753-26d3-464e-aa00-c6b5c2bf70fa
		summarizeBy: sum
		sourceColumn: QUOTE_SOURCES_COUNT_30_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUOTE_SOURCES_COUNT_60_DAY
		dataType: double
		isHidden
		lineageTag: 2909eca3-b949-4c6f-bcea-7ce9fbb59b7f
		summarizeBy: sum
		sourceColumn: QUOTE_SOURCES_COUNT_60_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUOTE_SOURCES_COUNT_90_DAY
		dataType: double
		isHidden
		lineageTag: 287d5669-9b10-4872-9b85-e75c36c170b6
		summarizeBy: sum
		sourceColumn: QUOTE_SOURCES_COUNT_90_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUOTE_MOVERS_COUNT
		dataType: double
		isHidden
		lineageTag: 8b4d61c6-3352-4e1d-bdf0-592412f3bda5
		summarizeBy: sum
		sourceColumn: QUOTE_MOVERS_COUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUOTE_MOVERS_COUNT_7_DAY
		dataType: double
		isHidden
		lineageTag: bbc7544c-68e9-4f60-9ccf-3f0aa754e580
		summarizeBy: sum
		sourceColumn: QUOTE_MOVERS_COUNT_7_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUOTE_MOVERS_COUNT_30_DAY
		dataType: double
		isHidden
		lineageTag: 15d017b5-ee81-4092-8d20-c3a68c3e57c0
		summarizeBy: sum
		sourceColumn: QUOTE_MOVERS_COUNT_30_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUOTE_MOVERS_COUNT_60_DAY
		dataType: double
		isHidden
		lineageTag: d5dccafa-25b1-4d92-87c5-87f541cc63f0
		summarizeBy: sum
		sourceColumn: QUOTE_MOVERS_COUNT_60_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUOTE_MOVERS_COUNT_90_DAY
		dataType: double
		isHidden
		lineageTag: 582b7f29-c0ee-4e97-82c9-abf6f1e1ef23
		summarizeBy: sum
		sourceColumn: QUOTE_MOVERS_COUNT_90_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUOTE_SOURCES_WITH_SIZE_COUNT
		dataType: double
		isHidden
		lineageTag: 88226fab-8df4-4559-8813-e6c39fbb24d1
		summarizeBy: sum
		sourceColumn: QUOTE_SOURCES_WITH_SIZE_COUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUOTE_SOURCES_WITH_SIZE_COUNT_7_DAY
		dataType: double
		isHidden
		lineageTag: a45a9a4e-e15a-47c6-a9dc-a71a62dbb2e0
		summarizeBy: sum
		sourceColumn: QUOTE_SOURCES_WITH_SIZE_COUNT_7_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUOTE_SOURCES_WITH_SIZE_COUNT_30_DAY
		dataType: double
		isHidden
		lineageTag: 03256e41-bb42-49e6-b599-d081e414801d
		summarizeBy: sum
		sourceColumn: QUOTE_SOURCES_WITH_SIZE_COUNT_30_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUOTE_SOURCES_WITH_SIZE_COUNT_60_DAY
		dataType: double
		isHidden
		lineageTag: ceba4dc9-fbe9-45de-af09-161d9d3d7cf5
		summarizeBy: sum
		sourceColumn: QUOTE_SOURCES_WITH_SIZE_COUNT_60_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUOTE_SOURCES_WITH_SIZE_COUNT_90_DAY
		dataType: double
		isHidden
		lineageTag: b2e59362-5eaf-49b6-ab52-e6a1f2e97dfc
		summarizeBy: sum
		sourceColumn: QUOTE_SOURCES_WITH_SIZE_COUNT_90_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BID_RATIO
		dataType: double
		isHidden
		lineageTag: 1c83ede7-9804-48c4-a1c2-57ae8c38afb4
		summarizeBy: sum
		sourceColumn: BID_RATIO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BID_RATIO_7_DAY
		dataType: double
		isHidden
		lineageTag: 3a7f1b50-008b-4912-b782-0a258272df70
		summarizeBy: sum
		sourceColumn: BID_RATIO_7_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BID_RATIO_30_DAY
		dataType: double
		isHidden
		lineageTag: 60cf6880-1fe8-4019-93e7-9021bcc43519
		summarizeBy: sum
		sourceColumn: BID_RATIO_30_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BID_RATIO_60_DAY
		dataType: double
		isHidden
		lineageTag: cea04b8b-cbee-4123-ae12-46f235905799
		summarizeBy: sum
		sourceColumn: BID_RATIO_60_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BID_RATIO_90_DAY
		dataType: double
		isHidden
		lineageTag: 4d2ab53c-e057-4988-ae83-ede93b163d2a
		summarizeBy: sum
		sourceColumn: BID_RATIO_90_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OFFER_RATIO
		dataType: double
		isHidden
		lineageTag: 7bc5f035-1da9-461d-a7de-ff1f21fa0cd5
		summarizeBy: sum
		sourceColumn: OFFER_RATIO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OFFER_RATIO_7_DAY
		dataType: double
		isHidden
		lineageTag: 85d6277e-a3c2-439c-b389-da74fb200f17
		summarizeBy: sum
		sourceColumn: OFFER_RATIO_7_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OFFER_RATIO_30_DAY
		dataType: double
		isHidden
		lineageTag: 612fbb01-0032-41b1-9d82-6bf4b66edecf
		summarizeBy: sum
		sourceColumn: OFFER_RATIO_30_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OFFER_RATIO_60_DAY
		dataType: double
		isHidden
		lineageTag: 5690d6ce-6be1-4033-9647-7dd4c133ede0
		summarizeBy: sum
		sourceColumn: OFFER_RATIO_60_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OFFER_RATIO_90_DAY
		dataType: double
		isHidden
		lineageTag: 20b7e116-ace7-4b53-bd5d-481b8a4fa968
		summarizeBy: sum
		sourceColumn: OFFER_RATIO_90_DAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ID_DATE
		dataType: string
		isHidden
		lineageTag: 0d528f82-9281-41c9-a827-1c4bee9ce9a3
		summarizeBy: none
		sourceColumn: ID_DATE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition INSTRUMENT_LIQUIDITY_SPGLOBAL = m
		mode: import
		source =
				let
				    Source = INSTRUMENT_LIQUIDITY,
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Data Provider Name] = "SPGLOBAL"))
				in
				    #"Filtered Rows"

	changedProperty = IsHidden

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

