table SOURCE_SYSTEM
	isHidden
	lineageTag: 3f0eddf9-f508-4e9d-90cd-79ffc066b836

	column SOURCE_SYSTEM_CODE
		dataType: string
		isHidden
		lineageTag: d38e26fa-4721-41b6-834a-dd37ed79711d
		summarizeBy: none
		sourceColumn: SOURCE_SYSTEM_CODE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SOURCE_SYSTEM_SHORT_NAME
		dataType: string
		isHidden
		lineageTag: 862a1c2f-9c51-48ba-862c-52de6544dc8b
		summarizeBy: none
		sourceColumn: SOURCE_SYSTEM_SHORT_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Source System Name'
		dataType: string
		isHidden
		lineageTag: a7b7c8e2-61d5-46ee-a27a-47a60ae4031a
		summarizeBy: none
		sourceColumn: Source System Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OBJECT_TYPE_CODE
		dataType: string
		isHidden
		lineageTag: 1c596912-d660-4682-9876-026c71c0b7a7
		summarizeBy: none
		sourceColumn: OBJECT_TYPE_CODE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Data Provider Name'
		dataType: string
		isHidden
		lineageTag: 058863ca-8f4a-4cee-9c6e-d4072ac0c1fe
		summarizeBy: none
		sourceColumn: Data Provider Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DATA_PERIOD_CODE
		dataType: string
		isHidden
		lineageTag: b1a8b403-3fe4-468d-8ac3-2d286834181a
		summarizeBy: none
		sourceColumn: DATA_PERIOD_CODE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CREATED_DATETIME
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 32a95f4a-e968-4896-9b37-aaf2047a1552
		summarizeBy: none
		sourceColumn: CREATED_DATETIME

		variation Variation
			isDefault
			relationship: 5f2f7b41-cd62-4245-9c89-ea6bd1a3fb36
			defaultHierarchy: LocalDateTable_288d6761-744b-42e4-8756-870aef0de891.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CREATED_BY_NAME
		dataType: string
		isHidden
		lineageTag: e3268b57-581f-45ff-a001-145e53d72202
		summarizeBy: none
		sourceColumn: CREATED_BY_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CREATED_BY_COMMENTS
		dataType: string
		isHidden
		lineageTag: fb3041e6-64b5-45ae-b512-6b9d6478cacb
		summarizeBy: none
		sourceColumn: CREATED_BY_COMMENTS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MODIFIED_DATETIME
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: c55daeab-5749-463d-b3de-20d65dd2072a
		summarizeBy: none
		sourceColumn: MODIFIED_DATETIME

		variation Variation
			isDefault
			relationship: 08fa4888-4457-4774-b80c-5a09b98a3561
			defaultHierarchy: LocalDateTable_29352872-9603-4685-b4e5-cf9733b8ece7.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MODIFIED_BY_NAME
		dataType: string
		isHidden
		lineageTag: 9dbf35e4-3b7a-4c78-91e3-9593777e3e0c
		summarizeBy: none
		sourceColumn: MODIFIED_BY_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MODIFIED_BY_COMMENTS
		dataType: string
		isHidden
		lineageTag: a1b7a279-7c69-4dbe-8735-2e3d6da71056
		summarizeBy: none
		sourceColumn: MODIFIED_BY_COMMENTS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition SOURCE_SYSTEM = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(snowflake_url,"ANALYST_WH_XS"),
				    HUB_Database = Source{[Name="HUB",Kind="Database"]}[Data],
				    JOB_Schema = HUB_Database{[Name="JOB",Kind="Schema"]}[Data],
				    SOURCE_SYSTEM_Table = JOB_Schema{[Name="SOURCE_SYSTEM",Kind="Table"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(SOURCE_SYSTEM_Table,{{"SOURCE_SYSTEM_NAME", "Source System Name"}, {"DATA_PROVIDER_NAME", "Data Provider Name"}})
				in
				    #"Renamed Columns"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

