table SOURCE_SYSTEM_STATUS
	isHidden
	lineageTag: 28829de7-93ba-4e8c-89bf-19259f711d30

	column 'Source System Status Identifier'
		dataType: double
		isHidden
		formatString: 0
		lineageTag: a85bb46b-abf0-4c31-9491-47779f68153e
		summarizeBy: none
		sourceColumn: Source System Status Identifier

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Calendar Date'
		dataType: dateTime
		isHidden
		formatString: yyyy-mm-dd
		lineageTag: 923af1cf-e751-4b65-b6fb-e507d5550feb
		summarizeBy: none
		sourceColumn: Calendar Date

		variation Variation
			isDefault
			relationship: 1e07d0f7-0656-401e-b2d9-6cba1dd85c54
			defaultHierarchy: LocalDateTable_8bdcfa18-d5c1-4acb-8356-acf3d3ebde5e.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column SOURCE_SYSTEM_CODE
		dataType: string
		isHidden
		lineageTag: b486ee8a-c495-439f-8d7b-0a401b542f99
		summarizeBy: none
		sourceColumn: SOURCE_SYSTEM_CODE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Active
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 60639370-de18-44c5-8c8d-4aa86a6ada5e
		summarizeBy: none
		sourceColumn: Active

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Batch Job Start Datetime'
		dataType: dateTime
		isHidden
		formatString: yyyy-mm-dd hh:nn
		lineageTag: 893ce28f-617c-495b-b830-6c85f163cbf9
		summarizeBy: none
		sourceColumn: Batch Job Start Datetime

		variation Variation
			isDefault
			relationship: 88965d3e-58e5-48c9-a09e-d74f400ea89a
			defaultHierarchy: LocalDateTable_0b2eea3a-e763-4121-ba9d-cdb6357ff1d7.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Batch Job End Datetime'
		dataType: dateTime
		isHidden
		formatString: yyyy-mm-dd hh:nn
		lineageTag: e57494b3-b0dc-40e7-bff5-427c95cf4a3c
		summarizeBy: none
		sourceColumn: Batch Job End Datetime

		variation Variation
			isDefault
			relationship: b3795557-b820-4204-bdea-b0b4ec4280d1
			defaultHierarchy: LocalDateTable_780c56ae-0f98-45ab-96ed-bcc4a9432301.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column BATCH_JOB_OUTPUT_DESCRIPTION
		dataType: string
		isHidden
		lineageTag: b032935a-6719-458c-9488-ef7106dcabbe
		summarizeBy: none
		sourceColumn: BATCH_JOB_OUTPUT_DESCRIPTION

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BATCH_JOB_NAME
		dataType: string
		isHidden
		lineageTag: 9da5239f-56c8-4977-9c94-b86c91c1700d
		summarizeBy: none
		sourceColumn: BATCH_JOB_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OBJECT_INSTANCE_NAME
		dataType: string
		isHidden
		lineageTag: 5463fd2d-26af-4433-b704-a021547c3628
		summarizeBy: none
		sourceColumn: OBJECT_INSTANCE_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OBJECT_INSTANCE_IDENTIFIER
		dataType: double
		isHidden
		lineageTag: a38da2e7-db59-4b40-9fa6-98e099090b77
		summarizeBy: sum
		sourceColumn: OBJECT_INSTANCE_IDENTIFIER

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Created Datetime'
		dataType: dateTime
		isHidden
		formatString: yyyy-mm-dd hh:nn
		lineageTag: 2f166cd0-39c3-452c-8a2b-7c3a25ef2726
		summarizeBy: none
		sourceColumn: Created Datetime

		variation Variation
			isDefault
			relationship: 0dc528c6-a55a-430c-9e61-fe96d15cc8a6
			defaultHierarchy: LocalDateTable_a1af1871-650d-4236-b534-bb9f54a2ac8c.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column CREATED_BY_NAME
		dataType: string
		isHidden
		lineageTag: 6e7c3d50-500e-4895-91dc-fe80a464612d
		summarizeBy: none
		sourceColumn: CREATED_BY_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CREATED_BY_COMMENTS
		dataType: string
		isHidden
		lineageTag: e936c96a-f5a3-41b7-9a81-8f76bbdadba2
		summarizeBy: none
		sourceColumn: CREATED_BY_COMMENTS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MODIFIED_DATETIME
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 2fa87b64-6f08-44f8-9cb5-942ad61514cf
		summarizeBy: none
		sourceColumn: MODIFIED_DATETIME

		variation Variation
			isDefault
			relationship: d9211688-489e-4be5-bd30-56134e457f82
			defaultHierarchy: LocalDateTable_1672ad37-0d39-44cb-a98f-aa27d4a55614.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MODIFIED_BY_NAME
		dataType: string
		isHidden
		lineageTag: 8c0c240b-27bf-435f-87ec-eba9346c2138
		summarizeBy: none
		sourceColumn: MODIFIED_BY_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MODIFIED_BY_COMMENTS
		dataType: string
		isHidden
		lineageTag: 7f989186-4f2a-4d90-aedf-d56403fa912c
		summarizeBy: none
		sourceColumn: MODIFIED_BY_COMMENTS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Days Since Refresh' = DATEDIFF([Calendar Date],TODAY(), DAY)
		isHidden
		formatString: 0
		lineageTag: e12763db-974f-4ae5-ad7f-85f39809ebd5
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition SOURCE_SYSTEM_STATUS = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(snowflake_url,"ANALYST_WH_XS"),
				    HUB_Database = Source{[Name="HUB",Kind="Database"]}[Data],
				    JOB_Schema = HUB_Database{[Name="JOB",Kind="Schema"]}[Data],
				    SOURCE_SYSTEM_STATUS_Table = JOB_Schema{[Name="SOURCE_SYSTEM_STATUS",Kind="Table"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(SOURCE_SYSTEM_STATUS_Table,{{"ACTIVE_INDICATOR", "Active"}, {"CALENDAR_DATE", "Calendar Date"}, {"BATCH_JOB_END_DATETIME", "Batch Job End Datetime"}, {"BATCH_JOB_START_DATETIME", "Batch Job Start Datetime"}, {"CREATED_DATETIME", "Created Datetime"}, {"SOURCE_SYSTEM_STATUS_IDENTIFIER", "Source System Status Identifier"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([Active] = true))
				in
				    #"Filtered Rows"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

