table TRANSACTION
	isHidden
	lineageTag: a738f40b-4cc9-45fd-8e3d-b30631e68dc2

	measure 'YTD Notional' = TOTALYTD(sum('TRANSACTION'[QUANTITY]),'TRANSACTION'[TRADE_DATE])
		formatString: #,0
		isHidden
		lineageTag: 98051165-3acd-48af-ba2b-79bfb8601841

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'MTD Notional' = TOTALMTD(sum('TRANSACTION'[QUANTITY]),'TRANSACTION'[TRADE_DATE])
		formatString: #,0
		isHidden
		lineageTag: 0717c950-9072-4a86-b7e8-f35956b8bb9b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'WTD Notional' = TOTALMTD(sum('TRANSACTION'[QUANTITY]),'TRANSACTION'[TRADE_DATE])
		formatString: 0
		isHidden
		lineageTag: ea9ced44-dacd-4eba-89e5-9ea50ae3d186

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	column SOURCE_SYSTEM_CODE
		dataType: string
		isHidden
		lineageTag: 92db5acf-5de5-4e21-8b29-c41ac62c9247
		summarizeBy: none
		sourceColumn: SOURCE_SYSTEM_CODE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SOURCE_SYSTEM_SHORT_NAME
		dataType: string
		isHidden
		lineageTag: 465e4b52-b659-43c7-8590-ed91abcb7999
		summarizeBy: none
		sourceColumn: SOURCE_SYSTEM_SHORT_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SOURCE_SYSTEM_NAME
		dataType: string
		isHidden
		lineageTag: 09f8b47d-b3e4-4a92-a351-aa6a24969bd9
		summarizeBy: none
		sourceColumn: SOURCE_SYSTEM_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SOURCE_SYSTEM_STATUS_IDENTIFIER
		dataType: double
		isHidden
		lineageTag: 653a5b9d-b7ef-4738-b110-627dcade4fb9
		summarizeBy: sum
		sourceColumn: SOURCE_SYSTEM_STATUS_IDENTIFIER

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DATA_PROVIDER_NAME
		dataType: string
		isHidden
		lineageTag: de5050b9-3a25-458a-86e9-33727dbe755f
		summarizeBy: none
		sourceColumn: DATA_PROVIDER_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column INSTRUMENT_IDENTIFIER
		dataType: string
		isHidden
		lineageTag: ba6cb8b3-919f-4595-a6cd-febe6db4d08a
		summarizeBy: none
		sourceColumn: INSTRUMENT_IDENTIFIER

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PORTFOLIO_IDENTIFIER
		dataType: string
		isHidden
		lineageTag: 9a77dd40-a922-4a27-a469-df6685db18dd
		summarizeBy: none
		sourceColumn: PORTFOLIO_IDENTIFIER

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CALENDAR_DATE
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: f7088070-d2fc-4c20-a69b-f06176f8916e
		summarizeBy: none
		sourceColumn: CALENDAR_DATE

		variation Variation
			isDefault
			relationship: ff9e6e3b-91f6-44ae-80a8-1501a331cac6
			defaultHierarchy: LocalDateTable_a4224767-099b-4a8c-ae22-b6067e1841ee.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TRADE_DATE
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: f85fe83d-e1e6-44b8-84cc-3dfb047c6b4f
		summarizeBy: none
		sourceColumn: TRADE_DATE

		variation Variation
			isDefault
			relationship: 74eb2119-75e0-4aea-a85c-4fca36b34452
			defaultHierarchy: LocalDateTable_3a5f2399-2bd4-4dfe-9028-26563f404ab7.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TRANSACTION_CODE
		dataType: string
		isHidden
		lineageTag: 5da6f362-ec5b-48a4-9d70-cd846b8db0ed
		summarizeBy: none
		sourceColumn: TRANSACTION_CODE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column QUANTITY
		dataType: double
		isHidden
		lineageTag: 339c50dc-6971-47aa-a24d-484b1a231d53
		summarizeBy: sum
		sourceColumn: QUANTITY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PRICE
		dataType: double
		isHidden
		formatString: 0.000
		lineageTag: ad3cb66c-2df8-4741-b236-c805ea115cd6
		summarizeBy: sum
		sourceColumn: PRICE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ACCRUED_INTEREST_AMOUNT
		dataType: double
		isHidden
		lineageTag: 8825cafd-2fe1-48ce-b4b0-98023afb527c
		summarizeBy: sum
		sourceColumn: ACCRUED_INTEREST_AMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CASH_AMOUNT
		dataType: double
		isHidden
		lineageTag: b3e1d8c0-e747-498c-8feb-8243e8902d32
		summarizeBy: sum
		sourceColumn: CASH_AMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SETTLEMENT_DATE
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: beea40ce-6de3-4928-9ae0-f84ed49705dc
		summarizeBy: none
		sourceColumn: SETTLEMENT_DATE

		variation Variation
			isDefault
			relationship: 2cf1eb3c-49ac-4b20-bda8-5af016ae7af3
			defaultHierarchy: LocalDateTable_498f6fa8-c6e3-49c4-9e82-89a939869e17.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TRADE_IDENTIFIER
		dataType: double
		isHidden
		lineageTag: a1caaed7-97ac-4ff2-8724-e559297f190d
		summarizeBy: sum
		sourceColumn: TRADE_IDENTIFIER

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TRANSACTION_IDENTIFIER
		dataType: double
		isHidden
		lineageTag: 9a518553-371e-4c28-9541-88d7c11166ad
		summarizeBy: sum
		sourceColumn: TRANSACTION_IDENTIFIER

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EXECUTING_BROKER_IDENTIFIER
		dataType: string
		isHidden
		lineageTag: 4fa98a51-e54d-4b29-8f64-161c35c3be2b
		summarizeBy: none
		sourceColumn: EXECUTING_BROKER_IDENTIFIER

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EXECUTING_BROKER_NAME
		dataType: string
		isHidden
		lineageTag: 150812fe-14dd-4585-8e8a-4532b758b1a7
		summarizeBy: none
		sourceColumn: EXECUTING_BROKER_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TRANSACTION_TYPE_IDENTIFIER
		dataType: double
		isHidden
		lineageTag: d9a60cb8-0e6b-4f6e-82d8-b62539fdc259
		summarizeBy: sum
		sourceColumn: TRANSACTION_TYPE_IDENTIFIER

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COUNTERPARTY_IDENTIFIER
		dataType: string
		isHidden
		lineageTag: 3013059d-7315-4d68-9de1-b1f3d3d947f1
		summarizeBy: none
		sourceColumn: COUNTERPARTY_IDENTIFIER

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column COUNTERPARTY_NAME
		dataType: string
		isHidden
		lineageTag: cb82ee7c-b656-4737-9311-190d819644b5
		summarizeBy: none
		sourceColumn: COUNTERPARTY_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SIGNED_QUANTITY
		dataType: double
		isHidden
		lineageTag: 0d791733-c315-4f55-877c-6cfe757a5abd
		summarizeBy: sum
		sourceColumn: SIGNED_QUANTITY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TRADE_CURRENCY_CODE
		dataType: string
		isHidden
		lineageTag: e728e051-99a5-4460-b921-2b35e5017929
		summarizeBy: none
		sourceColumn: TRADE_CURRENCY_CODE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IS_PRIMARY_INDICATOR
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 045174ce-b12e-4fba-aa97-b12aec027774
		summarizeBy: none
		sourceColumn: IS_PRIMARY_INDICATOR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TRANSACTION_ALLOCATION_IDENTIFIER
		dataType: string
		isHidden
		lineageTag: 2194b442-8961-4071-945a-a3249b04a10d
		summarizeBy: none
		sourceColumn: TRANSACTION_ALLOCATION_IDENTIFIER

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ALLOCATION_ACCOUNT_IDENTIFIER
		dataType: string
		isHidden
		lineageTag: b2354029-d247-46f9-aae5-89f2da33e6fa
		summarizeBy: none
		sourceColumn: ALLOCATION_ACCOUNT_IDENTIFIER

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ALLOCATION_FRACTION
		dataType: double
		isHidden
		lineageTag: 5ae2f503-a8d4-4a02-98be-2fa1d5fa8af7
		summarizeBy: sum
		sourceColumn: ALLOCATION_FRACTION

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TRANSACTION_ALLOCATION_QUANTITY
		dataType: string
		isHidden
		lineageTag: 954769e6-4a42-43ce-ac6c-021afc0055a5
		summarizeBy: none
		sourceColumn: TRANSACTION_ALLOCATION_QUANTITY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TRANSACTION_ALLOCATION_SETTLEMENT_AMOUNT
		dataType: string
		isHidden
		lineageTag: dc35ec6b-e63c-4d0f-9921-df0f28feaa0d
		summarizeBy: none
		sourceColumn: TRANSACTION_ALLOCATION_SETTLEMENT_AMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CURRENT_FACE_AMOUNT
		dataType: double
		isHidden
		lineageTag: a46e30c0-e6ec-46bd-8f01-b1738fd3aada
		summarizeBy: sum
		sourceColumn: CURRENT_FACE_AMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ORIGINAL_FACE_AMOUNT
		dataType: double
		isHidden
		lineageTag: 1c1169eb-ab61-4d61-9ba1-f04b1657e4e9
		summarizeBy: sum
		sourceColumn: ORIGINAL_FACE_AMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PRINCIPAL_AMOUNT
		dataType: double
		isHidden
		lineageTag: 02acc4a3-9930-4981-9ea0-2a8bded0f9cc
		summarizeBy: sum
		sourceColumn: PRINCIPAL_AMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COMMISSION_AMOUNT
		dataType: double
		isHidden
		lineageTag: 07021ad4-54a9-4777-8d21-780e80201ea7
		summarizeBy: sum
		sourceColumn: COMMISSION_AMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SEC_FEE_AMOUNT
		dataType: double
		isHidden
		lineageTag: 66cd65a3-ca62-4676-88a0-4416c0e73d5e
		summarizeBy: sum
		sourceColumn: SEC_FEE_AMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SETTLEMENT_AMOUNT
		dataType: double
		isHidden
		lineageTag: c8a98cfc-af2f-4549-af5a-28b7f7839fe4
		summarizeBy: sum
		sourceColumn: SETTLEMENT_AMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SETTLEMENT_CURRENCY_CODE
		dataType: string
		isHidden
		lineageTag: 80700066-cb07-474c-a373-0e11c5717f98
		summarizeBy: none
		sourceColumn: SETTLEMENT_CURRENCY_CODE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TRANSACTION_STATUS_CODE
		dataType: string
		isHidden
		lineageTag: 71ac3ab5-b993-4557-92e9-125f94b5fd4b
		summarizeBy: none
		sourceColumn: TRANSACTION_STATUS_CODE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PORTFOLIO_MANAGER_IDENTIFIER
		dataType: string
		isHidden
		lineageTag: 7ad96bb9-f498-4bd2-87ed-90aeeff11ae8
		summarizeBy: none
		sourceColumn: PORTFOLIO_MANAGER_IDENTIFIER

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TRADER_IDENTIFIER
		dataType: string
		isHidden
		lineageTag: c2c142a5-6ed6-42c5-b1eb-3742268800c4
		summarizeBy: none
		sourceColumn: TRADER_IDENTIFIER

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column INSERTED_AT_DATETIME
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 5b9ac4eb-028a-4fdf-b1d3-e16c9fd1a2a2
		summarizeBy: none
		sourceColumn: INSERTED_AT_DATETIME

		variation Variation
			isDefault
			relationship: 8faf9478-5322-4cc1-adb0-f0afbd5727ea
			defaultHierarchy: LocalDateTable_6af199c7-9740-4517-b968-a2d7c4f7e35c.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column INSERTED_BY_NAME
		dataType: string
		isHidden
		lineageTag: 25d8e0c4-43c0-4747-9301-d3f8a2949c8b
		summarizeBy: none
		sourceColumn: INSERTED_BY_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UPDATED_AT_DATETIME
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 84a1623f-cd4d-45a2-9338-ecc13654fbc4
		summarizeBy: none
		sourceColumn: UPDATED_AT_DATETIME

		variation Variation
			isDefault
			relationship: 5dbb7e8b-a5af-44b4-8e6f-89be2a7cfcc6
			defaultHierarchy: LocalDateTable_fab7c1ee-5fe7-4a84-9844-f7151a17c7bc.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UPDATED_BY_NAME
		dataType: string
		isHidden
		lineageTag: f6981fcc-8e8d-4f6f-af0d-8d4bed4cc21f
		summarizeBy: none
		sourceColumn: UPDATED_BY_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition TRANSACTION = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(#"snowflake_url","ANALYST_WH_XS"),
				    HUB_Database = Source{[Name="HUB",Kind="Database"]}[Data],
				    POSITION_Schema = HUB_Database{[Name="POSITION",Kind="Schema"]}[Data],
				    TRANSACTION_View = POSITION_Schema{[Name="TRANSACTION",Kind="View"]}[Data]
				in
				    TRANSACTION_View

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

